baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'My New Hugo Site'

theme = "hugo-blog-awesome"

[[params.socialIcons]]
name = "github"
url = "https://github.com/hugo-sid"

[params]
  goToTop = true

  