baseURL = 'https://emadadel4.github.io/'
languageCode = 'en'
title = 'Emad Adel'
paginate = 2

[taxonomies]
  author = "authors"

[languages.en]
  contentDir = 'content/en/'
  authorsDir = 'content/en/authors'
  languageCode = 'en-US'
  languageDirection = 'ltr'
  languageName = 'English'
  weight = 1

[languages.ar]
  contentDir = 'content/ar/'
  authorsDir = 'content/ar/authors'

  languageCode = 'ar'
  languageDirection = 'rtl'
  languageName = 'عربي'
  weight = 2

[Params]
 dateFormat = "Jan 2, 2006"